version: '3'

services:
  tr-app:
    container_name: tr-app
#    build: .
    image: siro5643/tr-app:latest
    ports:
      - "80:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=dev
    networks:
      - tr-network
    depends_on:
      - tr-db
      - tr-redis
  tr-db:
    image: mysql:8.0.37
    container_name: tr-mysql
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - tr-network
    env_file:
      - account_info.env
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
  tr-redis:
    image: redis:7.4.2
    container_name: tr-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/var/lib/redis
      - ./redis.conf:/usr/local/etc/redis/redis.conf
    networks:
      - tr-network
    command:
      - redis-server
      - /usr/local/etc/redis/redis.conf

networks:
  tr-network:
    driver: bridge

volumes:
  db_data:
  redis_data: