version: '3'

services:
  tr-db:
    image: mysql:8.0.37
    container_name: tr-mysql
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - tr-network
    env_file:
      - account_info.env
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
  tr-redis:
    image: redis:7.4.2
    container_name: tr-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/var/lib/redis
    networks:
      - tr-network

networks:
  tr-network:
    driver: bridge

volumes:
  db_data:
  redis_data: