spring:
  application:
    name: ticketReservationProject

  config:
    import:
      - classpath:account_info.yml
#      - classpath:redisson.yml

  # DB
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/trDB?characterEncoding=UTF-8&serverTimezone=Asia/Seoul&useSSL=false&allowPublicKeyRetrieval=true
    username: ${db.username}
    password: ${db.password}
  # JPA
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true

  # Redis
  data:
    redis:
      host: ${redis.host}
      port: ${redis.port}
      password: ${redis.password}

  jwt:
    secretKey: ${jwt.secretKey}

# log
logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type.descriptor.sql.BasicBinder: trace


